### ISSUE TITLE
Is there support for swagger 3+?

### ISSUE THREAD

**Issue by vorant94** [mtennoe/swagger-typescript-codegen#120]
Hi there! I am looking for swagger codeine solution for my angular app and found your package... But when I started to try it I got error that `Only Swagger 2 specs are supported`... Why is it so? Should I hope to get also Swagger 3 support in this lib? Or maybe have I missed some configuration?

**Comment by mtennoe** [comment]
Hey! I am sorry to say that there is currently no support for Swagger/OpenAPI 3, and we sadly don't have the capacity to look into that at the moment. I am very happy if someone want's to give it a shot though!
