### ISSUE TITLE
version  3.0 ??

### ISSUE THREAD

**Issue by brook-w** [mtennoe/swagger-typescript-codegen#125]
if (opts.swagger.swagger !== "2.0") {
        throw new Error("Only Swagger 2 specs are supported");
    }

**Comment by mtennoe** [comment]
Hi! The generator currently only supports Swagger 2, and there is sadly no bandwidth to look into 3.0 in the nearest future. Very happy if someone want's to do a pull request though :)

**Comment by evokeego** [comment]
Ya I'm in the same boat @brook-w . Currently using [api-spec-converter](https://www.npmjs.com/package/api-spec-converter) to downgrade my openapi v3 to swagger v2 before converting
