### ISSUE TITLE
Enable prettier

### ISSUE THREAD

**Issue by mtennoe** [mtennoe/swagger-typescript-codegen#34]
Prettier should be run on precommit to ensure consistent styling

**Comment by Markionium** [comment]
As part of this work we should also remove jshint

In lintCode:
```
// TODO: This seems like a weird leftover from the typescript cleanup? We probably don't need to support lint at all?
// Maybe run the result through tsc to make sure it's valid typescript and then beautify by providing a beautify function?
```

![image](https://user-images.githubusercontent.com/2134901/50816650-7d630280-1321-11e9-9055-6b31d6105a71.png)

**Comment by mtennoe** [comment]
Done as part of #52
