### ISSUE TITLE
Package version not updated

### ISSUE THREAD

**Issue by sbusch** [mtennoe/swagger-typescript-codegen#58]
Release version is 1.9.2, but version in package.json is still on 1.9.0, maybe due to changed release workflow w/ Travis CI?

(I'm not expired in these things, but there's at least "npm version", and more tools which even collect changelogs from git commits. What are you using/are you planning to use?)

**Comment by mtennoe** [comment]
Yup, there are some auth issues with the Travis deployment (seems that it doesnt handle 2factor auth very well) blocking that flow. I will take a look and fix it tomorrow, and ensure the whole pipeline works as expected

**Comment by Markionium** [comment]
We should probably use `npm version`(It's mostly been an oversight from me not informing Marius :P)

Those releases are also not in `npm` (So assuming you're usually installing from npm you should get 1.9.0)

**Comment by mtennoe** [comment]
@Markionium - Lets sync when I'm back in the office tomorrow

**Comment by mtennoe** [comment]
Having the release pipeline is overkill currently, so I removed the releases and will continue releasing manually for now (meaning 1.9.0 is the latest version). Will fix travis deployment properly whenever we need start needing it ofc.
