### ISSUE TITLE
Version 1.9.7 not packaged correctly

### ISSUE THREAD

**Issue by OlPainless** [mtennoe/swagger-typescript-codegen#69]
Hi again!

It seems the npm package of version 1.9.7 is not quite up to date. Looking at a diff between npm packages for 1.9.6 and 1.9.7 I see that `package.json` is updated, and the `allOf.json` test spec is included, but the changes to `object.js` mapper are not there. 

Perhaps there was some issue when publishing?

Kind regards,
Andreas

**Comment by mtennoe** [comment]
Curious! Could be a problem where it didnt build properly before publishing. I did a rebuild and republish now, and the lib folder contains the updated object.js mapper now, so hopefully the publish worked properly (version 1.9.8). Does that version work for you?

**Comment by OlPainless** [comment]
Version 1.9.8 works, thanks!
