### ISSUE TITLE
Allow deprecated methods to be processed

### ISSUE THREAD

**Issue by OlPainless** [mtennoe/swagger-typescript-codegen#70]
At the moment, codegen does not support generating client endpoints for deprecated methods. However, I have a use case where I'd need that specific functionality.

I've been thinking that it should be fairly straight forward to add a configuration option for processing deprecated methods (off by default, for backwards compatibility). What do you think, does this sound like an idea? I'd be happy to implement it.

Kind regards,
Andreas

**Comment by mtennoe** [comment]
Sounds like a good idea! Go for it! :)

**Comment by OlPainless** [comment]
I have made changes which seem to work, but I am a bit unsure how this should be tested; the normal test suite only tests that the generated code is valid, but there is no apparent way to see whether or not a method is included or not. Any ideas how this could be tackled?

**Comment by mtennoe** [comment]
Sounds like we should add some extra tests for this in the process then. One idea would be to attempt to call one of the specific deprecated methods in a jet test. If the test breaks due to the method not being defined if its excluded (and runs successfully vice versa), that should be sufficient

**Comment by OlPainless** [comment]
Maybe we're going through this the wrong way? Perhaps it would be easiest to just put this in a normal unit test, and check whether or not the method is added depending on the options.

I feel it might make the tests a bit brittle if we check that a specific function is generated or not, as it depends a lot on the templates (which don't have any specific tests at the moment).

**Comment by mtennoe** [comment]
Good point, that is a lot better (and easier)!
