### ISSUE TITLE
change interface of ResponseWithBody<S, T> to use <S extends number, T>

### ISSUE THREAD

**Issue by Kosta-Github** [mtennoe/swagger-typescript-codegen#79]
change interface of `ResponseWithBody<S, T>` to use `<S extends number, T>`

otherwise I am getting this errors:
```
Interface 'ResponseWithBody<S, T>' incorrectly extends interface 'Response'.
  Types of property 'status' are incompatible.
    Type 'S' is not assignable to type 'number'.
```
this is for typescript `3.5` and `@types/superagent`=`4.1.1`

**Comment by mtennoe** [comment]
@Kosta-Github - Thank you for reporting and creating a PR to fix this!
Merged and published as 1.10.1
